on:
  push:
    branches:
      - main
name: 🚀 Deploy main api on push

jobs:
  web-deploy:
    name: 🎉 Main Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.PROD_HOSTNAME }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          server-dir: ${{ secrets.PROD_DIR }}
          local-dir: ./
          exclude: "[**/.git*/**, **/node_modules/**, **/src/logs/**]"
          
    